spring:
  application:
    name: loopus_be
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://loopus-postgres:5432/loopus_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
logging:
  level:
    org:
      hibernate:
        SQL: trace
        orm:
          jdbc:
            bind: trace
    root: warn

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /api
